kind: Deployment
apiVersion: apps/v1
metadata:
  name: gcp-filestore-csi-controller
  namespace: gcp-filestore-csi-driver
spec:
  template:
    spec:
      containers:
      - name: gcp-filestore-driver
        imagePullPolicy: Always
      imagePullSecrets:
      - name: gcr-json-key

