kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: gcp-filestore-csi-node
  namespace: gcp-filestore-csi-driver
spec:
  template:
    spec:
      containers:
      - name: nfs-services
        imagePullPolicy: Always
      imagePullSecrets:
      - name: gcr-json-key
