apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-restore
  namespace: gcp-filestore-csi-driver
spec:
  dataSource:
    name: basic-pvc-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: small-basic-rwx
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1.2Ti
