apiVersion: v1
kind: PersistentVolume
metadata:
  name: preprov-vol
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle: "modeInstance/us-central1-a/try-1-zonal/vol1"
    volumeAttributes:
      ip: 10.4.234.2
      volume: vol1

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podvpc
spec:
  resources:
    requests:
      storage: 1Ti
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: preprov-vol
