apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-restore
  namespace: gcp-filestore-csi-driver
spec:
  dataSource:
    name: small-pvc-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: small-zonal-rwx
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
