apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zonal-small-0
  namespace: gcp-filestore-csi-driver
spec:
  resources:
    requests:
      storage: 0.1Ti
  storageClassName: small-zonal-rwx
  accessModes:
  - ReadWriteMany
