apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: small-zonal-rwx
provisioner: filestore.csi.storage.gke.io
parameters:
  tier: zonal
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
